### PR TITLE
Update revision triggers if coming from 1.7.0 or earlier

### LINKED ISSUE #192: Automatically update revision triggers when upgrading to 1.7
Release 1.7.0 changed the revision triggers so that they skip logging in revision table updates that did not really change values. This ticket is to make sure existing triggers are upgraded when upgrading the extension.

### PR DESCRIPTION
**Pull request by strk**
This is to effectively get the new feature of skipping empty updates
Closes #192

To be backported to 1.7 branch

### CODE REVIEW

**Comment by palmerj** [comment]
Are we going to drop PG 9.3 testing?

**Comment by strk** [comment]
Good idea. It looks like Bionic and PG 9.3 don't play nicely toghether...
Also 9.3 is not supported anymore upstream: https://www.postgresql.org/support/versioning/

Will drop

**Comment by imincik** [comment]
> Are we going to drop PG 9.3 testing?

I think so, I had to drop PG 9.3 from packaging because PGDG removed support.

**Comment by strk** [comment]
Done, can you please approve ?

**Pull request merged**
