### PR TITLE
Drop debian/control from repo

### PR DESCRIPTION
**Pull request by strk**
It is generated by 'make deb' so doesn't need to be in the source
repository.

### CODE REVIEW

**Comment by imincik** [comment]
@strk , I don't agree with that change, `control` file is mandatory for packaging. Please don't do it

**Comment by strk** [comment]
You mean for services which create packages automatically ? Because manual packaging works fine by running `make deb` ...

**Comment by imincik** [comment]
Yes, I think (not 100 % sure) that src package without `control` file is invalid and it can make problems for example when using Debian build services.

**Comment by strk** [comment]
You mean debian source package ?
Ideally we'd have a makefile rule for that too (`deb-src`?) - I'm
unable to write one at the moment because I still hadn't understood
the procedure (see #29).

**Comment by imincik** [comment]
Yes, I mean source package. For example, if you upload package to official Debian builder, it won't give you a chance to run `make` before build. I think it will complain.

**Comment by imincik** [comment]
@strk I am not sure what your problem was. I remember something about limiting Pg versions which are supported - for that we have `debian/pgversions` file.

**Comment by strk** [comment]
I reported my problem as a separate ticket: https://github.com/linz/postgresql-tableversion/issues/108

**Pull request closed without merging**
