### PR TITLE
[debian] provide a postgresql-agnostic package "tableversion"

### LINKED ISSUE #95: Provide PostgreSQL-agnostic debian package
The `postgresql-<VERSION>-tableversion` package contains both the extension and the loader and the loader template. Instead it would be useful to have a the extension agnostic parts be in a separate package `tableversion` for other packages to rely upon.

### PR DESCRIPTION
**Pull request by strk**
Closes #95

Includes package install test

### CODE REVIEW

**Comment by strk** [comment]
The `postgresql-xx-tableversion` package in this first stub will NOT contain the schema loader, while the `tableversion` package will.

**Comment by imincik** [comment]
This task is still relevant.

**Comment by strk** [comment]
The conflict (now resolved) was due to debian/control being changed both in master and here. There's no reason for that file to be in the repository, IMHO

**Comment by strk** [comment]
@palmerj thanks for testing, I've pushed 731b43c to fix the empty directory thing, could you please re-test ?

**Pull request merged**
