### PR TITLE
Add foreign key constraints to revision tables

### LINKED ISSUE #135: Add foreign key constraints to versioned table data
Table-specific revision tables might be good to have a foreign key constraints to table_version.revision table. To be verified performance cost of this. \cc @palmerj @imincik

### PR DESCRIPTION
**Pull request by strk**
Closes #135

### CODE REVIEW

**Comment by palmerj** [comment]
Did we check out the performance impact? Sorry if we already discussed this!

**Comment by strk** [comment]
The purpose of this PR is to let @imincik  test performance implications in a test environment (AWS).
Same applies for #121, which should have a minor impact

**Comment by imincik** [comment]
Still relevant.

**Comment by strk** [comment]
Added stalebot ignore label, hopefully it works. We still want to test performance penalty of this, as it brings higher consistency to the database

**Comment by imincik** [comment]
This task is still relevant.

**Comment by imincik** [comment]
This task is still relevant.

**Comment by strk** [comment]
Bad bot !

**Comment by strk** [comment]
still relevant

**Comment by imincik** [comment]
This task is still relevant.

**Comment by l0b0** [comment]
Closed in favour of #228.

**Pull request closed without merging**
