### PR TITLE
Fix installation of sharedir

### PR DESCRIPTION
**Pull request by strk**
Was bogus in previous commit

### CODE REVIEW

**Comment by strk** [comment]
Sorry Jeremy, previous version in #203 was not correct (nested tableversion directory in sharedir).
I guess tests should be improved..

**Comment by strk** [comment]
Tests added, let's see if it helps

**Comment by strk** [comment]
Tests are failing because rather than using `/usr/bin/table_version-loader`, the test script is hitting `/usr/lib/postgresql/11/bin/table_version-loader` which seems to be installed by the same package. This needs be fixed

**Comment by strk** [comment]
I was wrong, the binary installed in PostgreSQL directory does NOT come from a package, so either we have a broken `make uninstall` or there's something else which installed it (upgrade tester?)

**Comment by strk** [comment]
Confirmed, it was the upgrade tester leaving stuff around. Will think how to deal with it better.

**Comment by palmerj** [comment]
> Sorry Jeremy, previous version in #203 was not correct (nested tableversion directory in sharedir).
I guess tests should be improved..

No problem. I only reviewed the code and didn't run the code to check the output for the last commit. Yes more tests would help. I will redo some packaging checks now

**Comment by strk** [comment]
Thanks, fixed with 999a199

**Pull request merged**
