### PR TITLE
Fix insert/delete count output from ver_apply_table_differences

### LINKED ISSUE #39: Wrong returns from ver_apply_table_differences
The `ver_apply_table_differences` is documented to return the number of records inserted into, updated in and deleted from the original table, but the return has a `delete` count which is instead the `insert` count. Check this out:

```
create table table_original(i int primary key, t text);
create table table_new(i int primary key, t text);
insert into table_new values (1,'first record');
SELECT
            number_inserts,
            number_updates,
            number_deletes
        FROM
            table_version.ver_apply_table_differences(
                'table_original', 'table_new', 'i'
            );
NOTICE:  Generating difference data for table_original
NOTICE:  Completed generating difference data for table_original
NOTICE:  Deleting from table_original using difference data
NOTICE:  Updating table_original using difference data
NOTICE:  Inserting into table_original using difference data
NOTICE:  Finished updating table_original using difference data
 number_inserts | number_updates | number_deletes
----------------+----------------+----------------
              0 |              0 |              1
(1 row)

test=# select * from table_new;
 i |      t
---+--------------
 1 | first record
(1 row)
```

The call clearly *inserted* one record to the original table, but the function returned 1 as the number of deletes instead.

### PR DESCRIPTION
**Pull request by strk**
Closes #39

### CODE REVIEW

**Comment by strk** [comment]
NOTE: this change lacks a focused testcase (and the existing ones might expect wrong output, we'll see)

**Comment by strk** [comment]
Ok this definitely needs a test as the current one pass, which means there's no test for the specific bug.
And on second though it's better not to backport to 1.2 branch because that branch doesn't have the autogenerated upgrade script :)

**Comment by strk** [comment]
Great, the test does its job. It fail with PostgreSQL 9.2, 9.3 and 9.4 while passing with 9.5 and 9.6 :)
It is about the order of items coming out of the function, adding an ORDER BY should fix this

**Comment by imincik** [comment]
@strk , thanks for very detailed fix of this bug.

**Pull request merged**
