### PR TITLE
Add package building and publishing steps to CI

### PR DESCRIPTION
**Pull request by strk**
Builds packages using linz-software-repository action
Publish packages:
    - to "dev" repository on push
    - to "test" repository on tag

### CODE REVIEW

**Comment by strk** [comment]
Just needs the packagecloud secret to move on (better done at org level @imincik ?)

**Comment by strk** [comment]
@imincik this is ready for review now. It only publishes packages when either tagging or pushing to "master" or "packagecloud" branches.

It tests packages in every pull-request + before publishing.

Trigger on tag is yet to be tested (as it needs a tag to test)

**Comment by imincik** [comment]
@strk , can you merge now ? I am very interested how packages publishing will go.

**Comment by imincik** [comment]
Then we can merge the rest of repos.

**Comment by imincik** [comment]
I approved all repos

**Pull request merged**
