### PR TITLE
[travis] Use Bionic (18.04) distribution

### PR DESCRIPTION
**Pull request by strk**
... let's see if it works at first :)

### CODE REVIEW

**Comment by strk** [comment]
I can reproduce the problem on a `bionic` (`Ubuntu 18.04`) virtual machine with:

> make installcheck-upgrade PREPAREDB_UPGRADE_FROM=1.1.0

The problem is:

> pg_prove -d contrib_regression test/sql
test/sql/base.pg ..... psql:test/sql/preparedb:7: ERROR:  syntax error at or near "01 usr  0.01 sys +  0.05 cusr  0.00 csys =  0.07 CPU)
Result: FAIL

Looking into it

**Comment by strk** [comment]
Reducing the problem to:
> contrib_regression=# create extension table_version version '1.1.0';
ERROR:  syntax error at or near "

The console gets stuck there.
I think I remember having seen this due to use of `echo` in `Makefile`, which was fixed in 2dee5082e0e89e4cf2430b566e8013ac1afd92be

As we're installing tagged software, using not binary packages but rather building them from source, we're hitting that bug with old code. Not sure how to fix this, other than monkey-patching the code prior to build it or using a binary package (but I don't think we do have binary packages available for bionic and old versions...)

**Comment by imincik** [comment]
@strk , is this ready for review  ?

**Comment by strk** [comment]
Yes, ready and working

**Pull request merged**
