### PR TITLE
Have travis test debian packaging

### PR DESCRIPTION
**Pull request by strk**
See #26

### CODE REVIEW

**Comment by strk** [comment]
@imincik this attempt of mine fails with:

> dpkg-source: error: can't build with source format '3.0 (quilt)': no upstream tarball found at ../postgresql-tableversion_1.2.0.orig.tar.{bz2,gz,lzma,xz}

Maybe you know what it means ...

**Comment by strk** [comment]
note that what Travis runs is what the README suggests to run for [building the debian package](https://github.com/linz/postgresql-tableversion/blob/master/README.md#building-debian-packaging).

**Comment by strk** [comment]
Reading debian packaging tutorial I understand that a core concept for packaging is the "source tarball", but this project has no "make dist" Makefile rule to generate a tarball :/

I'll be reading https://vincent.bernat.im/en/blog/2016-pragmatic-debian-packaging and try to finally learn to deal with debian packages (sounds about time..)

**Comment by strk** [comment]
There, only building binary package fixed it. I filed the issue in a separate ticket #29

**Comment by imincik** [comment]
It is OK just add `-b` switch and build only binary debs for now.

**Pull request merged**
