### PR TITLE
[debian] Support PostgreSQL versions from 9.3 and higher

### LINKED ISSUE #108: debian/control is modified by `make deb`
After running `make deb`, `git diff` shows:
```
diff --git a/debian/control b/debian/control
index dab77e5..692d0f8 100644
--- a/debian/control
+++ b/debian/control
@@ -9,6 +9,17 @@ Homepage: http://www.linz.govt.nz
 Vcs-Git: git://github.com/linz/postgresql-tableversion.git
 Vcs-Browser: https://github.com/linz/postgresql-tableversion
 
+Package: postgresql-9.2-tableversion
+Architecture: all
+Depends: ${misc:Depends},
+         postgresql-9.2
+Recommends:
+Description: PostgreSQL table versioning extension, recording row modifications
+ and its history. The extension provides APIs for accessing snapshots of a table
+ at certain revisions and the difference generated between any two given
+ revisions. The extension uses a PL/PgSQL trigger based system to record and
+ provide access to the row revisions
+
 Package: postgresql-9.3-tableversion
 Architecture: all
 Depends: ${misc:Depends},
```

Basically a section for PostgreSQL 9.2 is added.

I'd like to drop debian/control completely but @imincik reports doing so might break some workflows (automated package building on some systems, see #105)

### PR DESCRIPTION
**Pull request by imincik**
Closes #108

### CODE REVIEW

**Comment by strk** [comment]
If we stop testing `<9.3` in Travis maybe we should update the README to say we don't support anything older than 9.3 ?

**Comment by imincik** [comment]
I am personally ok with dropping support of `<9.3`.

**Comment by strk** [comment]
Me too. Let's just then document in README and CHANGELOG for 1.5.0. Do you want to do it or shall I ?

**Comment by dwsilk** [comment]
Does this affect the LINZ Corp servers that are still on `9.1`?

**Comment by strk** [comment]
@dwsilk the code would probably still work but won't be (1) packaged for 9.1 and (2) tested by travis [9.1 is already untested by travis]

**Comment by imincik** [comment]
@dwsilk , thanks for pointing this out. 9.1 and 9.2 are not longer supported, so we decided to drop them from packages and testing, but as @strk said, code will most probably work.

**Pull request merged**
