### PR TITLE
Do not assume consistent ordering of revision table columns (fix for #109)

### PR DESCRIPTION
**Pull request by palmerj**

### CODE REVIEW

**Comment by palmerj** [comment]
Hi @strk please review this PR. You might want to add some additional unit tests as well. Things were a little rushed on Friday afternoon trying to get the data released, so I didn't add anymore tests that what have already been developed. For example adding column with use a SQL keyword as a name.

**Comment by imincik** [comment]
@strk will work on it this week

**Comment by strk** [comment]
I've added the test, but it was so convoluted that I'm wondering if it makes sense for `table_version` to support that kind of change. Basically the problem arises when the `table_version.public_xxx_revision` table structure mismatches with the one of the original table `public.xxx`. Would it make more sense to complain loudly about that occurrence instead of silently doing our best ?

**Comment by strk** [comment]
@palmerj mind you: I've rebased and squashed your 3 commits together so you'll need to reset your branch if you want to still be able to pull & push to the `trigger_colum_order` branch

**Pull request merged**
