### PR TITLE
handle TRUNCATE

### PR DESCRIPTION
**Pull request by strk**
See #204

### CODE REVIEW

**Comment by strk** [comment]
Ok, `TRUNCATE FOR EACH ROW  triggers are not supported so we'll need a different trigger to disable TRUNCATE, I'm afraid

**Comment by imincik** [comment]
> Ok, TRUNCATE FOR EACH ROW triggers are not supported so we'll need a different trigger to disable TRUNCATE, I'm afraid

@strk , is this PR finished then or not ?

**Comment by strk** [comment]
It's finished: we'll be using a second trigger.

**Comment by imincik** [comment]
`lds` schema tables are versioned (just checked in prod DB). So that 'not supported truncation' exception looks problematic now.

**Comment by strk** [comment]
See https://github.com/linz/linz-lds-bde-schema/pull/206

**Pull request merged**
