### PR TITLE
Add `make deb` rule

### LINKED ISSUE #49: [travis fails] Error: debian/control needs updating from debian/control.in. Run 'pg_buildext updatecontrol'.
Travis is failing since commit https://github.com/linz/postgresql-tableversion/commit/28629ca61c8bd91a77502041b72892086732f462 due to:
```
Error: debian/control needs updating from debian/control.in. Run 'pg_buildext updatecontrol'.
```

### PR DESCRIPTION
**Pull request by strk**
Removes generated debian/control from repository
Has travis use the new rule

Fixes #49 and #44

### CODE REVIEW

**Comment by strk** [comment]
Travis seems happy, proving the `make deb` rule works great.
@imincik I'd merge this so to be able to move on with other PRs (like #48 for git version detection)
We might want to backport this to 1.3 branch too

**Comment by strk** [comment]
part of this PR is the removal of debian/config (as it's created by an external command from debian/control.in) so it needs to be checked what are the implications of this on Launchpad...

**Comment by imincik** [comment]
Hi @strk , please wait with all Debian packaging changes for review. Please rollback this patch - "debain/control" file must be included in Git.

**Comment by imincik** [comment]
But `make deb` part is OK, this can go.

**Comment by strk** [comment]
The version of `debian.control` file that I removed from repository only had `postgresql-9.3` target, so failed the `make deb` on my machine. If we add it, shoudn't it have all the PostgreSQL versions, similar to the one I tried adding in b13d05ec51cc97f5a0cc213f01145f958b585ffd ?

**Comment by imincik** [comment]
`postgresql-9.3` is for purpose, because of Launchpad. Otherwise it will fail. But what you did in `make deb` was right approach - first run `pg_buildext updatecontrol` and then `git-buildpackage`. Also, you can override list of supported PostgreSQL versions for your build system by setting `PG_SUPPORTED_VERSIONS` and` DEB_PG_SUPPORTED_VERSIONS` variables. See: https://github.com/linz/linz-software-repository/wiki/Debian-packaging

**Pull request merged**
