### PR TITLE
Get table diff test

### PR DESCRIPTION
**Pull request by josephramsay**
Added pgTap tests to catch https://github.com/linz/postgresql-tableversion/issues/69

### CODE REVIEW

**Comment by strk** [comment]
Gah, travis fails for unrelated reason:
```pg_buildext: error: /usr/lib/postgresql/9.2/bin/pg_config does not exist```
Annoying!

**Comment by strk** [comment]
Try adding this snippet to .travis.yml:
```
group: deprecated-2017Q4
```
See https://blog.travis-ci.com/2017-12-12-new-trusty-images-q4-launch for more info

**Comment by josephramsay** [comment]
This is showing up in the travis logs `/usr/lib/postgresql/10/bin/psql: not found` Have seen the same on the tst2 build. Figured it was related to libpq-dev which seems to be misidentifying the postgres-version/bindir location

**Comment by josephramsay** [comment]
+ ok 95 - 1. Request char/integer set result
+ ok 96 - 2. Request char/varchar set result

**Comment by strk** [comment]
> /usr/lib/postgresql/10/bin/psql: not found

It looks like the travis configuration is not really working as expected (not testing multiple PotgreSQL versions). I guess it would also fail in master, I've started pr #72 to debug that, when fixed you can rebase against master.

**Comment by strk** [comment]
PR #72 confirms the problem occurs also in master, I'm on it.
Meanwhile (or for the future) please do not push branches to the official repo but rather to a fork of yours, so not to overload Travis (which otherwise builds both on push and PR)

**Comment by strk** [comment]
I could fix the travis build but only for PostgreSQL versions > 9.2 - guess I'll drop 9.2 testing for now

**Comment by strk** [comment]
Ok master build fixed (and no PostgreSQL version testing lost) - please rebase (and squash some ?) commits in this PR.

**Comment by dwsilk** [comment]
> Meanwhile (or for the future) please do not push branches to the official repo but rather to a fork of yours, so not to overload Travis (which otherwise builds both on push and PR)

It is also possible to turn off the **Build pushed branches** setting here: https://travis-ci.org/linz/postgresql-tableversion/settings

**Comment by josephramsay** [comment]
Closed in favour of https://github.com/linz/postgresql-tableversion/pull/73

**Pull request closed without merging**
