### PR TITLE
Add a ver_version() function

### PR DESCRIPTION
**Pull request by strk**
Needs a version bump an a proper upgrade procedure (see #35)

### CODE REVIEW

**Comment by strk** [comment]
Rebased to master, which includes travis upgrade testing. I'd expect travis to fail now, becuase there's no upgrade script to introduce the new function yet

**Comment by strk** [comment]
Ok so upgrade testing failed as expected, because the new function is not in the upgrade script.
But having the `ver_version` function in upgrade script would mean generating the upgrade script, which is only possible for updating to *current* version, while older versions are hard-coded.

So I think we should only include revision info in development versions and not final, with final always only having the official (tag) version.

In turn this because useless because there's no provision for upgrading between development versions.

So this PR is on old until upgrade procedure is reorganized (see #35)

**Comment by strk** [comment]
Great news ! The automatic generation of upgrade passes the upgrade test !

**Comment by strk** [comment]
As an added bonus, in latest commit, we can now also upgrade between development versions, using the `UPDATE TO <targetversion>next` and `UPDATE TO <targetversion>` trick, same as used with postgis.

**Comment by imincik** [comment]
@strk , as I said, great job !

**Pull request merged**
