### PR TITLE
Fix revision detection from git with debian packaging tags

### LINKED ISSUE #47: Revision detection from git doesn't work with Debian packaging tags
Revision detetion from git done in Makefile doesn't work with tags created by Debian packaging tools (for example tag: debian/1.3.0-1linz_trusty1).

`make` will finish with following error:
```
$ make
sed -e 's/@@VERSION@@/1.3.0/' META.json.in > META.json
sed -e 's/@@VERSION@@/1.3.0/;s/@@REVISION@@/debian/1.3.0-1linz_trusty1/' sql/20-version.sql.in > sql/20-version.sql
sed: -e expression #1, char 45: unknown option to `s'
Makefile:66: recipe for target 'sql/20-version.sql' failed
make: *** [sql/20-version.sql] Error 1
make: *** Deleting file 'sql/20-version.sql'
```

### PR DESCRIPTION
**Pull request by strk**
Fixes #47

### CODE REVIEW

**Comment by strk** [comment]
@imincik do we want to tag a 1.3.1 just for this change ? Or did you apply some workaround for debian packaging ?

**Comment by strk** [comment]
I've split this work in 2 commits to test that the Travis check was working in catching the failure before the fix, but unfortunately Travis is failing for an unrelated issue, reported as  #49 - so my plan is to wait for that issue to be fixed before re-testing this PR.

**Comment by strk** [comment]
I've merged the travis build fix and rebase this PR there (just the test, omitting the fix). Once I get a proper failure I push the fix.

**Comment by imincik** [comment]
> @imincik do we want to tag a 1.3.1 just for this change ? Or did you apply some workaround for debian packaging ?

Building first package was OK, tag was created after package was created. Next packaging will be in troubles if this problem wouldn't be fixed.

**Comment by strk** [comment]
ok so I will also backport this fix to 1.3 branch but not tag 1.3.1

**Comment by imincik** [comment]
yes, please backport it to 1.3 branch but not tag 1.3.1 .

**Comment by strk** [comment]
Backport PR is #51

**Pull request merged**
